<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-PUPFFT7" name="com.gurukula.AutomationTestgurkula.LTC_01_User_Authentication" tests="7" failures="0" timestamp="28 Apr 2019 19:49:26 GMT" time="97.277" errors="1">
  <testcase name="PTC_AM_01_Verify_User_Valid_login" time="24.845" classname="com.gurukula.AutomationTestgurkula.LTC_01_User_Authentication"/>
  <testcase name="PTC_AM_04_Verify_User_Valid_loginandLogout" time="13.548" classname="com.gurukula.AutomationTestgurkula.LTC_01_User_Authentication"/>
  <testcase name="PTC_AM_06_Verify_ResetPassword_button_isenabled_with_validemailid" time="13.664" classname="com.gurukula.AutomationTestgurkula.LTC_01_User_Authentication"/>
  <testcase name="PTC_AM_02_Verify_User_InValid_login" time="7.576" classname="com.gurukula.AutomationTestgurkula.LTC_01_User_Authentication">
    <error type="java.lang.AssertionError" message="invalid credentails not found expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: invalid credentails not found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.gurukula.AutomationTestgurkula.LTC_01_User_Authentication.PTC_AM_02_Verify_User_InValid_login(LTC_01_User_Authentication.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- PTC_AM_02_Verify_User_InValid_login -->
  <testcase name="PTC_AM_05_Verify_User_Valid_loginandLogout" time="8.741" classname="com.gurukula.AutomationTestgurkula.LTC_01_User_Authentication"/>
  <testcase name="PTC_AM_03_Verify_User_Valid_loginwithAutomaticLoginenabled" time="15.486" classname="com.gurukula.AutomationTestgurkula.LTC_01_User_Authentication"/>
  <testcase name="PTC_AM_07_Verify_ResetPassword_button_isenabled_with_invalidemailid" time="13.417" classname="com.gurukula.AutomationTestgurkula.LTC_01_User_Authentication"/>
</testsuite> <!-- com.gurukula.AutomationTestgurkula.LTC_01_User_Authentication -->
