<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-PUPFFT7" name="com.gurukula.AutomationTestgurkula.Authentication" tests="1" failures="1" timestamp="27 Apr 2019 22:01:42 GMT" time="0.003" errors="0">
  <testcase name="PTC_01_Verify_User_Valid_login" time="0.003" classname="com.gurukula.AutomationTestgurkula.Authentication">
    <failure type="java.io.FileNotFoundException" message="C:\Users\Gopi\Desktop\Selenium\Gurukul Workspace\AutomationTestgurkula\src\test\resources\propertyfiles\data.properties (The system cannot find the path specified)">
      <![CDATA[java.io.FileNotFoundException: C:\Users\Gopi\Desktop\Selenium\Gurukul Workspace\AutomationTestgurkula\src\test\resources\propertyfiles\data.properties (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.gurukula.resources.base.Launchurl(base.java:29)
	at com.gurukula.AutomationTestgurkula.Authentication.setupBeforeTest(Authentication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- PTC_01_Verify_User_Valid_login -->
</testsuite> <!-- com.gurukula.AutomationTestgurkula.Authentication -->
